#!/usr/bin/env node
//
// # Description
//
// Summarize the current page in a new tab, by processing it with the standalone readability
// library used for Firefox Reader View.
//
// # Prerequisites
//
//   - NODE_PATH might be required to point to your global node libraries:
//     export NODE_PATH=$NODE_PATH:$(npm root -g)
//   - Mozilla's readability library (npm install -g https://github.com/mozilla/readability.git)
//     NOTE: You might have to *login* as root for a system-wide installation to work (e.g. sudo -s)
//   - jsdom (npm install -g jsdom)
//   - qutejs (npm install -g qutejs)
//
// # Usage
//
// :spawn --userscript readability-js
//
// One may wish to define an easy to type command alias in Qutebrowser's configuration file:
// c.aliases = {"readability" : "spawn --userscript readability-js", ...}

const qute = require('qutejs')
const cheerio = require('cheerio')
const got = require('got')

got(process.env.QUTE_URL)
  .then((response) => {
    const C = cheerio.load(response.body)
    qute._execFifo(null, [
      'yank',
      'inline',
      `"[${C('title')[0]?.children[0]?.data}](${process.env.QUTE_URL})"`
    ])
  })
  .catch((err) => {
    if (err) {
      qute.messageError([`"${err}"`])
      return 1
    }
  })
